#!/usr/bin/env bun
/**
 * scripts/gen-pwa-assets.ts — embeds the PWA icon PNGs in the server.
 *
 * Why this exists: the server ships as a single compiled binary and as a
 * Docker image, and the web UI is inlined into one `index.html` by
 * `scripts/inline-web-ui.ts` (which also deletes `dist/assets/`). There is no
 * static-file route and no runtime asset directory, so icon bytes have to be
 * carried inside the binary. Base64 in a generated module is the boring
 * option that works in every one of those environments.
 *
 * Only the icon bytes are generated here. The manifest and the service worker
 * are hand-written source (`packages/server/src/pwa/`) so they stay reviewable
 * and testable; this script never touches them.
 *
 * Usage:  bun run scripts/gen-pwa-assets.ts [--check]
 *   --check  fail if the committed module differs from what would be written
 *            (used by the test suite so the PNGs and the module cannot drift)
 *
 * Regenerating the PNGs themselves is a separate, one-off art step that needs
 * ImageMagick/Pillow; see packages/web-ui/src/assets/brand/README.md.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const PWA_DIR = join(ROOT, "packages/web-ui/src/assets/pwa");
const OUT = join(ROOT, "packages/server/src/pwa-icons.generated.ts");

export interface PwaIconSource {
  /** Request path the server must answer. */
  path: string;
  /** File under packages/web-ui/src/assets/pwa. */
  file: string;
  sizes: string;
  purpose: "any" | "maskable";
}

/**
 * The icon set the manifest advertises. Chrome needs at least 192 and 512 for
 * the install prompt; `maskable` is what stops Android from shrinking the mark
 * inside a circle, so it is listed separately rather than replacing the
 * `any` icon.
 */
export const PWA_ICON_SOURCES: PwaIconSource[] = [
  { path: "/icons/icon-192.png", file: "icon-192.png", sizes: "192x192", purpose: "any" },
  { path: "/icons/icon-512.png", file: "icon-512.png", sizes: "512x512", purpose: "any" },
  {
    path: "/icons/icon-maskable-512.png",
    file: "icon-maskable-512.png",
    sizes: "512x512",
    purpose: "maskable",
  },
];

export function renderModule(): string {
  const rows = PWA_ICON_SOURCES.map((icon) => {
    const bytes = readFileSync(join(PWA_DIR, icon.file));
    const base64 = bytes.toString("base64").replace(/(.{76})/g, "$1\n");
    return [
      "  {",
      `    path: ${JSON.stringify(icon.path)},`,
      `    sizes: ${JSON.stringify(icon.sizes)},`,
      `    purpose: ${JSON.stringify(icon.purpose)},`,
      `    bytes: ${bytes.length},`,
      "    base64: [",
      base64
        .split("\n")
        .map((line) => `      "${line}",`)
        .join("\n"),
      '    ].join(""),',
      "  },",
    ].join("\n");
  });

  return `// GENERATED by scripts/gen-pwa-assets.ts — do not edit by hand.
//
// Base64 PNG bytes for the PWA icon set. Committed on purpose: the server has
// no runtime asset directory (see the script header), and a checked-in module
// keeps \`tsc\` and \`bun test\` working without running the generator first.
// \`pwa-assets.test.ts\` fails if this file drifts from the source PNGs.

/** One icon the manifest advertises and the server can serve. */
export interface PwaIconAsset {
  /** Request path. */
  path: string;
  /** Manifest \`sizes\` value. */
  sizes: string;
  /** Manifest \`purpose\` value. */
  purpose: "any" | "maskable";
  /** Decoded length in bytes; lets a test assert the blob is intact. */
  bytes: number;
  /** Base64 PNG payload. */
  base64: string;
}

export const PWA_ICONS: PwaIconAsset[] = [
${rows.join("\n")}
];
`;
}

const rendered = renderModule();

// Everything below only runs when the file is executed as a script, so the
// test suite can import `renderModule()` to compare against the committed
// module without rewriting it as a side effect.
if (import.meta.main) {

if (process.argv.includes("--check")) {
  const current = (() => {
    try {
      return readFileSync(OUT, "utf8");
    } catch {
      return "";
    }
  })();
  if (current !== rendered) {
    process.stderr.write(
      "gen-pwa-assets: packages/server/src/pwa-icons.generated.ts is stale — run `bun run scripts/gen-pwa-assets.ts`\n",
    );
    process.exit(1);
  }
  process.stdout.write("gen-pwa-assets: OK (generated module matches the source PNGs)\n");
  process.exit(0);
}

writeFileSync(OUT, rendered, "utf8");
const total = PWA_ICON_SOURCES.reduce(
  (sum, icon) => sum + readFileSync(join(PWA_DIR, icon.file)).length,
  0,
);
process.stdout.write(
  `gen-pwa-assets: wrote ${PWA_ICON_SOURCES.length} icons (${Math.round(total / 1024)} KB raw) to ${OUT.replace(`${ROOT}/`, "")}\n`,
);
}
